<?php

namespace AppBundle\Repository;

/**
 * BassRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BassRepository extends \Doctrine\ORM\EntityRepository
{
}
