<?php

namespace AppBundle\Repository;

use AppBundle\Utils\SQLUtils;
use Doctrine\ORM\EntityRepository;

/**
 * BassRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BassRepository extends EntityRepository
{
    public function searchBassesByQuery($query) {

        $normalizedQuery = SQLUtils::normalizeArrayElementsAndImplode(explode(" ", $query), '%');

       return $this->createQueryBuilder('bass')
            ->where("bass.normalizedData LIKE :query")
            ->setParameter('query', $normalizedQuery)
            ->getQuery()
            ->execute();
    }
}
