<?php

namespace AppBundle\Repository;

/**
 * UserRatingsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRatingsRepository extends \Doctrine\ORM\EntityRepository
{
}
